#!/bin/bash

export FACEBOOK_CLIENT_ID=FB_ID
export FACEBOOK_APP_SECRET=SECRET

export YELP_CONSUMER_KEY=Y_KEY
export YELP_CONSUMER_SECRET=Y_SEC
export YELP_TOKEN=Y_TOK
export YELP_TOKEN_SECRET=Y_TOK_SEC
export PG_CONNECTION_STRING=CONNECTION_STRING